#!/bin/sh

MINCAML_HOME=$(cd "$(dirname "$0")"/../ && pwd)
CP_DIR="$MINCAML_HOME/panda"
CP_DIR_PACKAGE="$CP_DIR/target/classes"
CP="jars/java-cup-11b-runtime.jar:$CP_DIR_PACKAGE/"
exec java -enableassertions -cp "$CP" org.panda.Main "$@"
